###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

appzum-mysql:
  image: mysql:5.7
  container_name: appzum-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=appzum
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass

appzum-webserver:
  image: phpdockerio/nginx:latest
  container_name: appzum-webserver
  volumes:
      - ./SiberianCMS/:/var/www/appzum
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8088:80"
  links:
   - appzum-php-fpm

appzum-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: appzum-php-fpm
  volumes:
    - ./SiberianCMS:/var/www/appzum
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - appzum-mysql
